### ISSUE TITLE
susepaste pastes blank paste

### ISSUE THREAD

**Issue by pr0fsmith** [openSUSE/paste#12]
Paste appears to be successful but when one navigates to the link, the paste is blank. Happens when I use paste with a command.

this is my command | susepaste

**Comment by cboltz** [comment]
Just tested, and it works for me.

Are you sure that your command produces a non-empty output? If in doubt, run it without `| susepaste` and with `2>/dev/null` (because stderr won't end up in the pipe to susepaste).

You can also test something like `echo test | susepaste`

**Comment by pr0fsmith** [comment]
It works sometimes and not others.  

This is the command I was trying to run
`python rssFetcher.py | susepaste`

This is the error I was trying to capture.
`# github.com/unidoc/unipdf/internal/license
/root/go/src/github.com/unidoc/unipdf/internal/license/license.go:31:96: undefined: os.UserHomeDir
# github.com/juruen/rmapi/config
/root/go/src/github.com/juruen/rmapi/config/config.go:40:20: undefined: os.UserConfigDir
# github.com/stretchr/testify/assert
/root/go/src/github.com/stretchr/testify/assert/assertions.go:1738:5: undefined: errors.Is
/root/go/src/github.com/stretchr/testify/assert/assertions.go:1761:6: undefined: errors.Is
/root/go/src/github.com/stretchr/testify/assert/assertions.go:1784:5: undefined: errors.As
/root/go/src/github.com/stretchr/testify/assert/assertions.go:1801:7: undefined: errors.Unwrap
/root/go/src/github.com/stretchr/testify/assert/assertions.go:1805:7: undefined: errors.Unwrap
# github.com/unidoc/unipdf/internal/license
/root/go/src/github.com/unidoc/unipdf/internal/license/license.go:31:96: undefined: os.UserHomeDir
# github.com/stretchr/testify/assert
/root/go/src/github.com/stretchr/testify/assert/assertions.go:1738:5: undefined: errors.Is
/root/go/src/github.com/stretchr/testify/assert/assertions.go:1761:6: undefined: errors.Is
/root/go/src/github.com/stretchr/testify/assert/assertions.go:1784:5: undefined: errors.As
/root/go/src/github.com/stretchr/testify/assert/assertions.go:1801:7: undefined: errors.Unwrap
/root/go/src/github.com/stretchr/testify/assert/assertions.go:1805:7: undefined: errors.Unwrap
# github.com/juruen/rmapi/config
/root/go/src/github.com/juruen/rmapi/config/config.go:40:20: undefined: os.UserConfigDir
./install.sh: line 14: ./rmapi: No such file or directory
`
But the command works fine for everything else.

**Comment by cboltz** [comment]
Your output looks like it went to stderr - and that doesn't end up in the pipe by default.

Instead of `python rssFetcher.py | susepaste`, please use `python rssFetcher.py 2>&1 | susepaste`. That will redirect stderr to stdout, which also means susepaste will "see" it.

**Comment by pr0fsmith** [comment]
Thanks. Problem solved

May 25, 2021 5:24:42 a.m. Christian Boltz ***@***.***>:

**Comment by cboltz** [comment]
I'm glad to hear that :-)
